apiVersion: v1
kind: Service
metadata:
  name: license-firmament-com
  namespace: sky-firmament
  labels:
    app: firmament-license
spec:
  selector:
    app: firmament-license
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32081
  type: NodePort
