apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-daemonset
  namespace: sky-firmament
spec:
  template:
    metadata:
      labels:
        app: "fluentd-daemon"
    spec:      
      containers:
      - name: fluentd-elasticsearch
        image: ading1977/fluentd-elasticsearch:1.22
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
        env:
        - name: FLUENTD_FLUSH_INTERVAL
          value: 10s
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: kubernetes.url
        - name: KUBERNETES_VERIFY_SSL
          value: "False"
        - name: "ELASTICSEARCH_HOST"
          value: "elasticsearch-logging"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: containers
          mountPath: /var/lib/docker/containers
      terminationGracePeriodSeconds: 0
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
